<?php
/**
 * TransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bitcoin API
 *
 * Blockchain Facilities
 *
 * OpenAPI spec version: 2.0.0
 * Contact: contato@astarlabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TransactionTest Class Doc Comment
 *
 * @category    Class */
// * @description Transaction
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Transaction"
     */
    public function testTransaction()
    {

    }

    /**
     * Test attribute "creationdate"
     */
    public function testPropertyCreationdate()
    {

    }

    /**
     * Test attribute "confirmationdate"
     */
    public function testPropertyConfirmationdate()
    {

    }

    /**
     * Test attribute "blockchaincreationdate"
     */
    public function testPropertyBlockchaincreationdate()
    {

    }

    /**
     * Test attribute "txid"
     */
    public function testPropertyTxid()
    {

    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {

    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {

    }

    /**
     * Test attribute "txsize"
     */
    public function testPropertyTxsize()
    {

    }

    /**
     * Test attribute "txhex"
     */
    public function testPropertyTxhex()
    {

    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {

    }

    /**
     * Test attribute "feepriority"
     */
    public function testPropertyFeepriority()
    {

    }

    /**
     * Test attribute "confirmations"
     */
    public function testPropertyConfirmations()
    {

    }

    /**
     * Test attribute "errormessage"
     */
    public function testPropertyErrormessage()
    {

    }

    /**
     * Test attribute "coin"
     */
    public function testPropertyCoin()
    {

    }

    /**
     * Test attribute "test"
     */
    public function testPropertyTest()
    {

    }

}
