<?php
declare(strict_types=1);
/**
 * SearchApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bitcoin API
 *
 * Blockchain Facilities
 *
 * OpenAPI spec version: 2.0.0
 * Contact: contato@astarlabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */
namespace AStar\Client;
//require "vendor/autoload.php";
require "../autoload.php";

use \AStar\Client\Configuration;
use \AStar\Client\ApiClient;
use \AStar\Client\ApiException;
use \AStar\Client\ObjectSerializer;

/**
 * SearchApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for searchByAPIID
     *
     * Get transaction informations by API ID.
     *
     */
    public function testSearchByAPIID() {
        $api = new Api\SearchApi();
        
        $token = new Token();
        $tokenParameter = $token->sign("YOUR PRIVATE KEY");

        $account = "2";
        $user  = "test";
        $pass = "test";
        $id = "243";
        $response = $api->searchByAPIID($tokenParameter, $account, $user, $pass, $id);
        print_r( $response);
    }

    /**
     * Test case for searchByContent
     *
     * Get transaction informations by file or string content.
     *
     */
    public function testSearchByContent()
    {

    }

    /**
     * Test case for searchByHash
     *
     * Get transaction informations by file or string hash.
     *
     */
    public function testSearchByHash()
    {

    }

}
